name: Test, Build, Deploy

on:
  push:

jobs:
  build:
    name: Build Docker Images
    runs-on: ubuntu-latest

    env:
      API_REPO: "pt-django-backend"
      NGINX_REPO: "nginx"
      ARTIFACT_NAME: "pt-django-backend-qa-imagedefinitions.json"

    steps:
      - name: Test Step
        run: echo "Hi"
